### PR TITLE
Fixes #23: Revisit JS docs

### LINKED ISSUE #23: Revisit JS docs
Find something simpler in terms of look and feel

### PR DESCRIPTION
**Pull request by postatum**
Fixes #23: Revisit JS docs.

Looks like in typedoc versions >0.15.0 minimal theme and files linking were improved.
Now it's possible to generate documentation from two separate files without externals and they get linked together. Because of this new docs UI looks very light and everything is linked together.

In future it would be nice to document AMF type definitions so it would more than just an API listing.

---

After this PR is merged, we should:
1. Regenerate JS docs (and gh pages docs) by running `./scripts/generate-gh-pages-docs.sh`;
2. Update `/docs` directory content in `master` with generated docs.

### CODE REVIEW

**Comment by jstoiko** [comment]
1) on the [current docs](https://raml-org.github.io/webapi-parser/js/classes/_webapi_parser_.webapibaseunit.html), below the collapsed `WebApiBaseUnit` submenu of the right menu bar, there are links to the following classes: `WebApiBaseUnitWithDeclaresModel`, `WebApiBaseUnitWithDeclaresModelAndEncodesModel`, `WebApiBaseUnitWithEncodesModel`. When I generate the docs on this `i23_revisit_js_docs` branch locally, those classes disappeared from the left menu. Is that intended? I can still see those classes under the `Hierarchy` block at the top of the page (under `Custom BaseUnit subclass which implements utility methods.`).
2) Under each property documentation block, I now see `Defined in merged.d.ts` under the `Inherited from <link>`. Where is that "merged.d.ts" coming from?

**Comment by postatum** [comment]
>     1. on the [current docs](https://raml-org.github.io/webapi-parser/js/classes/_webapi_parser_.webapibaseunit.html), below the collapsed `WebApiBaseUnit` submenu of the right menu bar, there are links to the following classes: `WebApiBaseUnitWithDeclaresModel`, `WebApiBaseUnitWithDeclaresModelAndEncodesModel`, `WebApiBaseUnitWithEncodesModel`. When I generate the docs on this `i23_revisit_js_docs` branch locally, those classes disappeared from the left menu. Is that intended? I can still see those classes under the `Hierarchy` block at the top of the page (under `Custom BaseUnit subclass which implements utility methods.`).

I've pulled this branch now and that page interface looks identical to me on both old and new docs.
Considering your 2nd comment, it may be possible that your git client failed to pull latest changes from the branch. Please make sure it did and then run:

```sh
$ ./scripts/generate-js-docs.sh
```


Also I've just switched to a newer Typedoc version. It adds a little to an interface but still nothing unnecessary.

**Comment by jstoiko** [comment]
I deleted the `./docs` folder and re-generated again and everything looks good.

**Comment by jstoiko** [comment]
will it make any difference when https://github.com/aml-org/amf/issues/577 will be closed?

**Comment by postatum** [comment]
> will it make any difference when [aml-org/amf#577](https://github.com/aml-org/amf/issues/577) will be closed?

No. It would be a matter of using "npm install" to install amf typings instead of downloading them with curl.

**Pull request merged**
